version: '3.7'

services:
    dev:
        build:
            context: .
        working_dir: /app
        volumes:
            - "..:/app"
        depends_on:
            - db_instance
        command: >
            bash -c "pwsh /app/_dev/init.ps1 && sleep infinity"
    
    db_instance:
        # image: mcr.microsoft.com/mssql/server:2019-latest
        image: ghcr.io/dah-dah-demos/solid-tribble-db:dev # 2021.06.22.19-dev
        environment:
            - ACCEPT_EULA=Y
            - SA_PASSWORD=P@ssw0rd12345
        ports:
            - 7601:1433
