name: publish

on: [push]

jobs:
  publish-solid-tribble-db-image:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
    - uses: actions/checkout@v2

    - name: 'update version'
      id: update-version
      shell: bash
      run: |
        buildDateNumber=$(date '+%Y.%m.%d')
        buildId=$GITHUB_RUN_NUMBER
        buildNumber="$buildDateNumber.$buildId"
        echo "$buildNumber"
        echo "::set-output name=BUILD_NUMBER::$buildNumber"

    - name: Build
      run: dotnet build --configuration release --verbosity normal /nologo /property:GenerateFullPaths=true
      working-directory: src/Tribble.Contacts

    - name: 'download backup files'
      shell: bash
      run: |
        mkdir __downloads && cd __downloads
        wget -q https://github.com/dah-dah-demos/stunning-memory/raw/main/files/demo.bak        
      #working-directory: ${GITHUB_WORKSPACE}
  
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build the solid-tribble-db Docker image
      run: |
        docker build --tag ghcr.io/dah-dah-demos/solid-tribble-db:${{ steps.update-version.outputs.BUILD_NUMBER }}-dev --tag ghcr.io/dah-dah-demos/solid-tribble-db:dev -f build/Dockerfile .
        docker push ghcr.io/dah-dah-demos/solid-tribble-db:${{ steps.update-version.outputs.BUILD_NUMBER }}-dev
        docker push ghcr.io/dah-dah-demos/solid-tribble-db:dev
