name: publish

on: [push]

jobs:
  publish-solid-tribble-db-image:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build the solid-tribble-db Docker image
      run: |
        docker build . --tag ghcr.io/dah-dah-demos/solid-tribble-db:latest
        docker run ghcr.io/dah-dah-demos/solid-tribble-db:latest
        docker push ghcr.io/dah-dah-demos/solid-tribble-db:latest
